project:
  type: website
  # output-dir: docs

website:
  title: "Mobile and Wearable Data Science"
  favicon: images/favicon.ico
  site-url: "https://wearableds.github.io"
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: events.qmd
        text: Events
      - href: publications.qmd
        text: Publications
      - href: involvement.qmd
        text: Get Involved
      - href: contact.qmd
        text: Contact
  page-footer:
    center: "Â© 2025 Mobile and Wearable Data Science"

format:
  html:
    theme: flatly
    toc: true
